string section_name       # name of the interface section
uint32 sensor_id          # id of the sensor to send request
string[] statuses         # list of status or status to send
uint8[] status_types      # 0: uint32, 1: uint16
---
string res                # response from the sensor
