/smart_radar:
  ros__parameters:
    adapters:
      adapter_0:
        hw_type: "eth"
        hw_dev_id: 4
        hw_iface_name: "enx002432163c8d"
        port: 55555
      adapter_1:
        hw_type: "can"
        hw_dev_id: 5
        hw_iface_name: "can0"
        baudrate: 500000
    master_data_serial_type: can_based
    master_inst_serial_type: can_based
    sensors:
      # As many as 10 sensors all named as "sensor_<number>" in increasing order of numbers,
      # e.g., sensor_0, sensor_1, etc. The list must start with sensor_0.
      # 
      # For supported model names and matching uifname values, refer to:
      # src/smartmicro_ros2_radars/umrr_ros2_driver/param/model_uif_catalogue.yaml
      #
      # Tip: version is encoded in the model name (e.g. *_v1_0_3).
      sensor_0:
        # The link of the sensor either 'can' or 'eth'
        link_type: "eth"
        # The publisher type of the sensor
        pub_type: "target"
        # The model of the connected sensor.
        model: "umrra4_v1_6_0"
        # Adapter id to which sensor is connected
        dev_id: 4
        # The client_id of the sensor/source, must be a unique integer.
        id: 100
        # The frame_id to be set to the published messages.
        frame_id: "umrr"
        # Specify the history size.
        history_size: 10
        # The ip address of the sensor or of the source acting as a sensor.
        ip: "192.168.11.11"
        inst_type: "port_based"
        data_type: "port_based"
        # The port to be used.
        port: 55555
        # The interface name of the sensor
        uifname: "umrra4_automotive"
        # The major version of the interface
        uifmajorv: 1
        # The minor version of the interface
        uifminorv: 6
        # The pathc version of the interface
        uifpatchv: 0
      sensor_1:
        # The link of the sensor either 'can' or 'eth'
        link_type: "can"
        # The publisher type of the sensor
        pub_type: "target"
        # The model of the connected sensor. Available models umrr11, umrr9d, umrr96,
        model: "umrra4_can_v1_6_0"
        # The client_id of the sensor/source, must be a unique integer.
        id: 200
        # Adapter id to which sensor is connected
        dev_id: 5
        inst_type: "can_based"
        data_type: "can_based"
        # The interface name of the sensor
        uifname: "umrra4_automotive"
        # The major version of the interface
        uifmajorv: 1
        # The minor version of the interface
        uifminorv: 6
        # The pathc version of the interface
        uifpatchv: 0
        # The frame_id to be set to the published messages.
        frame_id: "umrr"
        # Specify the history size.
        history_size: 10
