---
/**:
  ros__parameters:
      # This sets the iface_name in the hw_inventory.json
      # One sensor per adapter in case of CAN
      # For ethernet it is possible to have one adapter/interface for multiple sensors
      master_inst_serial_type: "port_based"
      master_data_serial_type: "port_based"
      adapters:
          adapter_0:
              hw_type: "eth"
              hw_dev_id: 3
              hw_iface_name: "eth0"
              port: 55555
